"""Configuration management subcommands.

This module provides CLI commands for managing simulation configurations.

Commands:
    - init: Generate configuration template
    - show: Display current configuration
    - validate: Validate configuration file

Example:
    $ autoflowcfd config init --template steady
    $ autoflowcfd config validate simulation.yaml
"""

import click
import json
from pathlib import Path
from loguru import logger


@click.group()
def config() -> None:
    """Configuration management commands.
    
    Create, validate, and manage YAML configuration files.
    
    Examples:
        # Create config template
        $ autoflowcfd config init --template steady
        
        # Validate config
        $ autoflowcfd config validate simulation.yaml
    """
    pass


@config.command()
@click.option("--template", "-t", type=click.Choice(["steady", "transient"]),
              required=True, help="Configuration template type")
@click.option("--output", "-o", type=click.Path(), default="config.yaml",
              help="Output file path")
def init(template: str, output: str) -> None:
    """Generate configuration file template.
    
    Create a YAML configuration template with sensible defaults
    for steady-state or transient simulations.
    
    Args:
        template: Template type (steady/transient)
        output: Output file path
    
    Examples:
        # Steady-state template
        $ autoflowcfd config init --template steady -o steady_config.yaml
        
        # Transient template
        $ autoflowcfd config init --template transient -o transient_config.yaml
    """
    from autoflowcfd.config import SteadyConfig, TransientConfig
    
    logger.info(f"Generating {template} configuration template")
    
    try:
        output_path = Path(output)
        
        if template == "steady":
            config_obj = SteadyConfig()
            template_content = f"""# AutoFlowCFD Steady-State Configuration
# Generated by 'autoflowcfd config init'

mode: steady

# Solver settings
backend: auto  # cpu, gpu, or auto
order: 3       # FR order (1, 2, or 3)
turbulence: sst_kw  # sst_kw, sa

# Convergence settings
max_iter: 5000
cfl_init: 0.1
cfl_max: 5.0
convergence_tol: 1.0e-6

# Output settings
output_dir: ./results
checkpoint_interval: 100
verbose: false
"""
        else:  # transient
            config_obj = TransientConfig()
            template_content = f"""# AutoFlowCFD Transient Configuration
# Generated by 'autoflowcfd config init'

mode: transient

# Solver settings
backend: auto  # cpu, gpu, or auto
order: 3       # FR order (1, 2, or 3)
turbulence: des  # des, ddes, les

# Time integration
time_integration: backward_euler  # backward_euler, rk2, rk3, ab3
dt: 1.0e-4     # Time step size (s)
total_time: 0.3  # Total physical time (s)

# Sampling settings
sample_interval: 10

# Output settings
output_dir: ./transient_results
checkpoint_interval: 100
verbose: false
"""
        
        # Write to file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(template_content)
        
        logger.info(f"Configuration template saved to {output_path}")
        click.echo(f"✓ Configuration template created: {output}")
        click.echo(f"  Type: {template}")
        click.echo(f"\nEdit this file to customize your simulation settings.")
    
    except Exception as e:
        logger.error(f"Failed to create config template: {e}")
        raise click.ClickException(f"Failed to create config template: {e}")


@config.command()
@click.argument("config_file", type=click.Path(exists=True))
@click.option("--json", "-j", "json_output", is_flag=True, help="Output as JSON")
def show(config_file: str, json_output: bool) -> None:
    """Display configuration file contents.
    
    Load and display a YAML configuration file with validation.
    
    Args:
        config_file: Path to YAML configuration file
        json_output: Output as JSON
    
    Examples:
        # Show config
        $ autoflowcfd config show simulation.yaml
        
        # JSON output
        $ autoflowcfd config show simulation.yaml --json
    """
    from autoflowcfd.config import ConfigLoader
    
    logger.info(f"Loading configuration: {config_file}")
    
    try:
        loader = ConfigLoader()
        config_obj = loader.load(config_file)
        
        # Convert to dict for display
        if hasattr(config_obj, '__dict__'):
            config_dict = vars(config_obj)
        else:
            config_dict = config_obj.__dict__
        
        if json_output:
            # Convert enums to strings
            def enum_serializer(obj):
                if hasattr(obj, 'value'):
                    return obj.value
                raise TypeError(f"Object of type {type(obj)} is not JSON serializable")
            
            click.echo(json.dumps(config_dict, indent=2, default=enum_serializer))
        else:
            click.echo(f"\nConfiguration: {config_file}")
            click.echo(f"{'='*60}")
            for key, value in config_dict.items():
                # Format enum values
                if hasattr(value, 'value'):
                    value = value.value
                click.echo(f"{key:<25} {value}")
            click.echo(f"{'='*60}")
    
    except Exception as e:
        logger.error(f"Failed to load configuration: {e}")
        raise click.ClickException(f"Failed to load configuration: {e}")


@config.command()
@click.argument("config_file", type=click.Path(exists=True))
@click.option("--json", "-j", "json_output", is_flag=True, help="Output as JSON")
def validate(config_file: str, json_output: bool) -> None:
    """Validate configuration file.
    
    Check configuration file for syntax errors and invalid values.
    
    Args:
        config_file: Path to YAML configuration file
        json_output: Output as JSON
    
    Examples:
        # Validate config
        $ autoflowcfd config validate simulation.yaml
        
        # JSON output
        $ autoflowcfd config validate simulation.yaml --json
    """
    from autoflowcfd.config import ConfigLoader
    
    logger.info(f"Validating configuration: {config_file}")
    
    try:
        loader = ConfigLoader()
        config_obj = loader.load(config_file)
        
        result = {
            "command": "config.validate",
            "status": "valid",
            "file": config_file,
            "mode": config_obj.mode if hasattr(config_obj, 'mode') else "unknown",
        }
        
        if json_output:
            click.echo(json.dumps(result, indent=2))
        else:
            mode = config_obj.mode if hasattr(config_obj, 'mode') else "unknown"
            click.echo(f"✓ Configuration is valid")
            click.echo(f"  File: {config_file}")
            click.echo(f"  Mode: {mode}")
    
    except Exception as e:
        logger.error(f"Configuration validation failed: {e}")
        result = {
            "command": "config.validate",
            "status": "invalid",
            "file": config_file,
            "error": str(e),
        }
        
        if json_output:
            click.echo(json.dumps(result, indent=2))
        
        raise click.ClickException(f"Configuration validation failed: {e}")
